import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillModal. */
export const i = {
  body: { padding: "20px 24px 24px" } satisfies CSSProperties,
  // Kept in the DOM (not display:none) so it stays reachable by label/role in
  // tests and by assistive tech; the visible affordance is the button beside it.
  fileInput: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  picker: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 16px",
    borderRadius: 10,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  pickerTitle: {
    fontSize: 13.5,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  pickerHint: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  status: { fontSize: 13, color: "var(--text-secondary)", marginTop: 14 } satisfies CSSProperties,
  error: {
    marginTop: 14,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--crit)",
  } satisfies CSSProperties,
  trustNotice: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    marginTop: 16,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  metaGrid: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: "6px 14px",
    marginTop: 16,
    fontSize: 13,
  } satisfies CSSProperties,
  metaKey: { color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  metaValue: { color: "var(--text-primary)", minWidth: 0, wordBreak: "break-word" } satisfies CSSProperties,
  warnings: {
    margin: "14px 0 0",
    paddingLeft: 18,
    fontSize: 12.5,
    lineHeight: 1.6,
    color: "var(--warn)",
  } satisfies CSSProperties,
  ignored: {
    marginTop: 16,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  ignoredHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    fontWeight: 600,
    marginBottom: 8,
  } satisfies CSSProperties,
  ignoredList: { margin: 0, paddingLeft: 18, maxHeight: 140, overflow: "auto" } satisfies CSSProperties,
  ignoredItem: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.7,
    wordBreak: "break-all",
  } satisfies CSSProperties,
  execTag: { marginLeft: 8, fontSize: 11, color: "var(--warn)" } satisfies CSSProperties,
  ignoredNote: { fontSize: 12, color: "var(--text-muted)", marginTop: 8, lineHeight: 1.5 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "18px 0 6px",
  } satisfies CSSProperties,
  markdown: {
    fontSize: 13,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    maxHeight: 280,
    overflow: "auto",
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10, width: "100%" } satisfies CSSProperties,
  footerNote: { flex: 1, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
