import type { CSSProperties } from "react";

/** Co-located styles for the agent Context tab. */
export const s = {
  wrap: { maxWidth: 860 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  hint: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 14,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  filterRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14 } satisfies CSSProperties,
  sectionHead: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 22,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  row: (opts: { dragging: boolean; unresolved: boolean }): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 8,
    border: `1px solid ${opts.unresolved ? "var(--crit)" : "var(--border)"}`,
    background: "var(--bg-surface)",
    opacity: opts.dragging ? 0.5 : 1,
  }),
  grip: {
    display: "grid",
    placeItems: "center",
    width: 20,
    height: 20,
    color: "var(--text-muted)",
    cursor: "grab",
  } satisfies CSSProperties,
  path: { fontSize: 13, color: "var(--text-primary)" } satisfies CSSProperties,
  rowRight: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 22,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  error: { fontSize: 12.5, color: "var(--crit)" } satisfies CSSProperties,
} as const;
